name: Docker CI

on:
  push:
    branches:
      - "main"
    paths:
      - 'deku/**'
      - 'node-configurator/**'
      - 'snapshot-downloader/**'
      - 'fluentd-loki/**'
  pull_request:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push node configurator
        id: docker_build_node_conf
        uses: docker/build-push-action@v2
        with:
          context: ./node-configurator
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Only push if on main branch
          push: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
          tags: |
            ghcr.io/marigold-dev/tezos-node-configurator:latest
            ghcr.io/marigold-dev/tezos-node-configurator:${{ github.sha }}

      - name: Build and push snapshot downloader
        id: docker_build_snapshot_dl
        uses: docker/build-push-action@v2
        with:
          context: ./snapshot-downloader
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Only push if on main branch
          push: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
          tags: |
            ghcr.io/marigold-dev/tezos-snapshot-downloader:latest
            ghcr.io/marigold-dev/tezos-snapshot-downloader:${{ github.sha }}

      - name: Build and push fluentd loki
        id: docker_build_fluentd_loki
        uses: docker/build-push-action@v2
        with:
          context: ./fluentd-loki
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Only push if on main branch
          push: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
          tags: |
            ghcr.io/marigold-dev/fluentd-loki:latest
            ghcr.io/marigold-dev/fluentd-loki:${{ github.sha }}
