name: Tezos Docker CI

on:
  workflow_dispatch:
    inputs:
      profile:
        required: true
        default: 'dev'
        description: 'dev | master | static'
      version:
        required: true
        default: 'master'
        description: 'commit or branch from Tezos'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push tezos
        id: docker_build_tezos
        uses: docker/build-push-action@v2
        with:
          context: ./tezos
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PROFILE=${{ github.event.inputs.profile }}
            TEZOS_VERSION=${{ github.event.inputs.version }}
          push: true
          tags: |
            ghcr.io/marigold-dev/tezos:${{ github.event.inputs.profile }}-${{ github.event.inputs.version }}-latest
            ghcr.io/marigold-dev/tezos:${{ github.sha }}

